image: debian:trixie

stages:
  - build

build-job:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y git cmake ninja-build libfreetype6-dev libglfw3-dev build-essential
  script:
    - cmake --version
    - ninja --version
    - cmake -G Ninja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -B build -S .
    - cmake --build build -j$(nproc)
  artifacts:
    paths:
      - build/
