if (WIN32)
    set(CMAKE_SYSTEM_NAME Windows)
    set(LLVM_PATH "C:/Program Files/LLVM/bin")
    set(CMAKE_CXX_COMPILER "${LLVM_PATH}/clang-cl.exe")
    set(CMAKE_C_COMPILER "${LLVM_PATH}/clang-cl.exe")
    set(CMAKE_LINKER "${LLVM_PATH}/lld-link.exe")
elseif(UNIX)
    set(CMAKE_CXX_COMPILER clang-cl)
    set(CMAKE_C_COMPILER clang-cl)
    set(CMAKE_LINKER lld-link)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_compile_options("-Wno-ignored-attributes")
