if (WIN32)
    set(CMAKE_SYSTEM_NAME Windows)
    set(CLANG_BIN "C:/msys64/clang64/bin")
    set(CMAKE_C_COMPILER "${CLANG_BIN}/clang.exe")
    set(CMAKE_CXX_COMPILER "${CLANG_BIN}/clang++.exe")
    set(CMAKE_LINKER "${CLANG_BIN}/lld-link.exe")
    set(MSYS_PATH "C:/msys64/clang64")
    include_directories(SYSTEM "${MSYS_PATH}/include")
elseif (UNIX)
    set(CMAKE_C_COMPILER clang)
    set(CMAKE_CXX_COMPILER clang++)
    set(CMAKE_LINKER lld-link)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
