if (WIN32)
    set(CMAKE_SYSTEM_NAME Windows)
    set(UCRT_BIN "C:/msys64/ucrt64/bin")
    set(CMAKE_C_COMPILER "${UCRT_BIN}/gcc.exe")
    set(CMAKE_CXX_COMPILER "${UCRT_BIN}/g++.exe")
    set(CMAKE_LINKER "${UCRT_BIN}/ld.exe")
    set(MSYS_PATH "C:/msys64/ucrt64")
    include_directories(SYSTEM "${MSYS_PATH}/include")
elseif (UNIX)
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_C_COMPILER gcc)
    set(CMAKE_CXX_COMPILER g++)
    set(CMAKE_LINKER ld)
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
